import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { JsonLd } from "@/components/seo/JsonLd";
import { buildOrganizationSchema, buildWebSiteSchema } from "@/lib/seo";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  // Theme-aware browser chrome tinting. The actual <html data-theme> is set
  // at runtime by the anti-flash script in <head>, but media queries here
  // give the OS a hint so PWA splash + iOS status bar match the preferred
  // theme out of the gate.
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#080808" },
    { media: "(prefers-color-scheme: light)", color: "#fafafa" },
  ],
  colorScheme: "light dark",
};

export const metadata: Metadata = {
  title: {
    default: "Dezignxo — 3D Asset Marketplace",
    template: "%s | Dezignxo",
  },
  description:
    "The leading platform for 3D & AR assets on the web. Browse, buy, and sell premium 3D models and materials.",
  keywords: [
    "3D assets",
    "3D models",
    "materials",
    "game assets",
    "digital marketplace",
    "AR assets",
    "3D graphics",
  ],
  authors: [{ name: "Dezignxo" }],
  creator: "Dezignxo",
  metadataBase: new URL(
    process.env.NEXTAUTH_URL ?? "http://localhost:3000"
  ),
  // Linked from <head>; the PWA manifest itself is generated by app/manifest.ts.
  manifest: "/manifest.webmanifest",
  // Stops mobile browsers from auto-linking phone numbers, addresses and
  // emails that happen to appear in copy — they aren't real CTAs.
  formatDetection: { telephone: false, address: false, email: false },
  openGraph: {
    type: "website",
    locale: "en_US",
    title: "Dezignxo — 3D & 2D Asset Marketplace",
    description:
      "The leading platform for 3D & AR assets on the web. Browse, buy, and sell premium digital assets.",
    siteName: "Dezignxo",
  },
  twitter: {
    card: "summary_large_image",
    title: "Dezignxo — 3D & 2D Asset Marketplace",
    description:
      "The leading platform for 3D & AR assets on the web.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  // Google Search Console ownership proof. Next emits the
  //   <meta name="google-site-verification" content="..." />
  // tag inside <head> automatically — same effect as pasting the
  // tag by hand, but driven by the Metadata API so it stays
  // co-located with the rest of our SEO config.
  verification: {
    google: "pFQoLqlGPJR7sOenhC9z737Zlnig0tGs7qOZCx_F3Wc",
  },
  // Canonical URL avoids www / apex / trailing-slash duplication. Per-
  // page metadata generators override this with their own absolute
  // canonical when relevant (e.g. asset detail).
  alternates: {
    canonical: process.env.NEXTAUTH_URL ?? "http://localhost:3000",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Anti-flash theme bootstrap.
            Runs synchronously BEFORE React hydrates and BEFORE first paint —
            so the user never sees a dark frame flicker through to light (or
            vice versa) on page load. Reads the saved choice from localStorage,
            falls back to the OS preference if nothing's saved. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('dezignxo.theme');if(!t){t=window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';}document.documentElement.setAttribute('data-theme',t);}catch(e){document.documentElement.setAttribute('data-theme','dark');}})();`,
          }}
        />
        {/* Site-wide structured data — Organization + WebSite with a
            SearchAction so Google can render the SERP sitelinks-search
            box for brand queries. */}
        <JsonLd schema={[buildOrganizationSchema(), buildWebSiteSchema()]} />
      </head>
      <body className="min-h-dvh bg-canvas text-primary antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
