import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#080808",
  colorScheme: "dark",
};

export const metadata: Metadata = {
  title: {
    default: "Designo — 3D Asset Marketplace",
    template: "%s | Designo",
  },
  description:
    "The leading platform for 3D & AR assets on the web. Browse, buy, and sell premium 3D models and materials.",
  keywords: [
    "3D assets",
    "3D models",
    "materials",
    "game assets",
    "digital marketplace",
    "AR assets",
    "3D graphics",
  ],
  authors: [{ name: "Designo" }],
  creator: "Designo",
  metadataBase: new URL(
    process.env.NEXTAUTH_URL ?? "http://localhost:3000"
  ),
  // Linked from <head>; the PWA manifest itself is generated by app/manifest.ts.
  manifest: "/manifest.webmanifest",
  // Stops mobile browsers from auto-linking phone numbers, addresses and
  // emails that happen to appear in copy — they aren't real CTAs.
  formatDetection: { telephone: false, address: false, email: false },
  openGraph: {
    type: "website",
    locale: "en_US",
    title: "Designo — 3D & 2D Asset Marketplace",
    description:
      "The leading platform for 3D & AR assets on the web. Browse, buy, and sell premium digital assets.",
    siteName: "Designo",
  },
  twitter: {
    card: "summary_large_image",
    title: "Designo — 3D & 2D Asset Marketplace",
    description:
      "The leading platform for 3D & AR assets on the web.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-dvh bg-canvas text-primary antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
